AWSTemplateFormatVersion: "2010-09-09"
Description: API Gateway service proxy to an SNS Topic
Resources:
  IngestTopic:
    Type: AWS::SNS::Topic
  APIGatewayIamRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "apigateway.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
  RolePolicies: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "sns-publish"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: "sns:Publish"
            Resource:
              Ref: IngestTopic
      Roles: 
        - 
          Ref: "APIGatewayIamRole"
  ApiGatewayRestApi: 
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "Service Proxy"
  ApiGatewayResourceIngest:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      PathPart: "ingest"
      RestApiId:
        Ref: ApiGatewayRestApi
  ApiGatewayMethodIngestPost:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: "POST"
      ResourceId:
        Ref: ApiGatewayResourceIngest
      RestApiId:
        Ref: ApiGatewayRestApi
      AuthorizationType: "NONE"
      Integration:
        Type: "AWS"
        IntegrationHttpMethod: "POST"
        Credentials:
          Fn::GetAtt:
            - APIGatewayIamRole
            - Arn
        Uri:
         Fn::Join:
           - ""
           - - "arn:"
             - Ref: AWS::Partition
             - ":apigateway:"
             - Ref: AWS::Region
             - ":sns:path//"
        RequestParameters:
          "integration.request.header.Content-Type": "'application/x-www-form-urlencoded'"
        RequestTemplates:
          "application/json":
            Fn::Join:
              - ""
              - - "Action=Publish&TopicArn=$util.urlEncode('"
                - Ref: IngestTopic
                - "')&Message=$util.urlEncode($input.body)"
        IntegrationResponses:
          - StatusCode: 200
            SelectionPattern: ""
            ResponseTemplates:
              "application/json": '{"body": "Message received"}'
      MethodResponses:
        - ResponseModels:
            "application/json": "Empty"
          StatusCode: 200
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: ApiGatewayRestApi
      StageName: "prod"
    DependsOn:
      ApiGatewayMethodIngestPost
Outputs:
  ServiceEndpoint:
    Description: "URL of the service proxy endpoint"
    Value:
      Fn::Join:
        - ""
        - - "https://"
          - Ref: ApiGatewayRestApi
          - ".execute-api."
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - "/prod"
